CREATE TABLE IF NOT EXISTS 'MY_TABLE'(
	'MY_TABLE_ID' int(11) NOT NULL AUTO_INCREMENT
	'TITLE' varchar(255) DEFAULT NULL,
    'MESSGAE' varchar(255) DEFAULT NULL,
'DETAIL' varchar(1000) DEFAULT NULL,
'CONTEXT' varchar(1000) DEFAULT NULL,
'PROCESS_ID' int(11) DEFAULT NULL,
'TITLE' varchar(255) DEFAULT NULL,
'TITLE' varchar(255) DEFAULT NULL,

PRIMARY KEY ('MY_TABLE_ID')
)ENGINE=InnoDB DEFAULT CHARSET=utf8

/* *** ADD A FIELD ***
* NOTES:
* -Always include AFTER_COLUMN_NAME even if the column is not being moved.
*/

Call IDEm_SP_DDL_UTIL_ADD_FIELD_IF_NOT_EXISTS ('MY_TABLE_NAME', "NEW_COLUMN_NAME", "DATATYPE". "AFTER_COLUMN_NAME")
-- Example
CALL IDEM_SP_DDL_UTIL_ADD_FIELD_IF_NOT_EXISTS ('MY_TABLE', 'newField1', 'INT NOT NULL DEFAULT 0', 'PROCESS_ID');
