DELIMITER$$
CREATE OR REPLACE FUNCTION 'CASEMGNT_UTIL_CONVERT_DATE_TIME' ('pinDate' VARCHAR(10), 'pinTime', VARCHAR(10)) RETURNS datetime
 RETURN STR_TO_DATE(concat(pinDate,LPAD(pinTime, 4, '0')),'%Y%m%d%H%i')$$
DELIMITER ;